version: '3.4'

services:
  reservation:
    image: reservation
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: reservation_admin
      POSTGRES_DB: db_reservation
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  postgres_data:
