version: '3.4'

services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 reservation.wsgi -c reservation/gunicorn/default.conf.py
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: reservation_admin
      POSTGRES_DB: db_reservation

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  postgres_data:
