# Generated by Django 4.0.4 on 2022-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_reservations_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservations",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
