# Generated by Django 4.0.4 on 2022-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_reservations_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservations",
            name="user",
        ),
    ]
