# Generated by Django 4.0.4 on 2022-04-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_reservations_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservations",
            name="table_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="app.tables",
            ),
        ),
    ]
