# Generated by Django 4.0.4 on 2022-04-16 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_reservations_table_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservations",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="reservations",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservations",
            name="table_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.tables"
            ),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
